# !sort -t / -k2

all:: installers
all:: tools
all:: sec
all:: casks
all:: net
all:: dev
all:: devcloud
all:: devpy
all:: devnode
all:: devc
all:: devsh
all:: devtf
all:: devlua
all:: devgo
all:: devnim
all:: music
all:: pandoc

minimal: pacman/base-devel     # sudo, which, sed, etc
minimal: brew/btop pacman/btop # c version of bpytop
minimal: brew/fd pacman/fd     # better find - used in fzf
minimal: cask/firefox
minimal: brew/fish pacman/fish
minimal: cask/font-hack-nerd-font
minimal: brew/fzf pacman/fzf
minimal: brew/git pacman/git pacman/git-lfs
minimal: brew/git-absorb pacman/git-absorb
minimal: brew/grep
minimal: brew/htop pacman/htop
minimal: brew/neovim pacman/neovim
minimal: brew/ripgrep pacman/ripgrep
minimal: brew/starship pacman/starship # shell prompt
minimal: brew/tldr pacman/tldr
minimal: brew/tree-sitter-cli pacman/tree-sitter-cli
minimal: cask/wezterm # gpu terminal emulator

installers: uv/python/3.14
installers: brew/go pacman/go # required for yay
installers: brew/volta yay/volta-bin
installers: brew/uv pacman/uv
installers: brew/ruby

tools: pacman/arch-install-scripts # genfstab
tools: brew/bash
tools: brew/bash-completion pacman/bash-completion
tools: brew/bat # cat+colors
tools: brew/colordiff pacman/colordiff
tools: brew/coreutils
tools: pacman/coreutils
tools: brew/cowsay
tools: uv/csvkit # sqlite on top of csv files
tools: brew/curl pacman/curl
tools: brew/diffutils
tools: brew/findutils
tools: brew/fortune
tools: brew/gawk
tools: brew/gnu-sed
tools: brew/gnu-tar
tools: brew/gnu-which
tools: brew/gzip
tools: brew/hint
tools: uv/httpie
tools: pacman/inetutils     # ships hostname
tools: volta/@jarred/git-peek # preview any github repo in vim
tools: brew/jq pacman/jq
tools: pacman/less
tools: brew/lolcat # colorful cats
tools: brew/lsd pacman/lsd
tools: pacman/lsof
tools: brew/make
tools: brew/moreutils
tools: brew/noti # notify when command finishes
tools: brew/openssh pacman/openssh
tools: brew/openssl@3
tools: brew/par yay/par      # adjust line width in text in vim
tools: brew/progress         # track progress of io programs like dd
tools: brew/source-highlight # used by less with default highlight
tools: brew/tree pacman/tree
tools: brew/unzip
tools: brew/watch
tools: brew/wget pacman/wget
tools: pacman/xclip
tools: pacman/xh brew/xh # httpie in rust
tools: pacman/xorg-xauth # X server auth
tools: pacman/xorg-xclock
tools: brew/yq yay/go-yq
tools: brew/dyff yay/dyff
tools: brew/zoxide pacman/zoxide # cd to folders quickly

sec: brew/browserpass
sec: brew/gnupg pacman/gnupg
sec: brew/gopass
sec: brew/gopass-jsonapi
sec: brew/paperkey     # just secret from gpg key
sec: brew/pass         # browserpass uses pass vs gopass
sec: brew/pinentry-mac # gpg pin enter gui
sec: brew/pwgen
sec: brew/ykman # yubikey manager cli version
sec: cask/yubico-authenticator
# sec: cask/yubico-yubikey-manager

casks: cask/adobe-creative-cloud
casks: cask/alfred
casks: cask/android-file-transfer
casks: cask/bartender
casks: cask/brave-browser
casks: cask/istat-menus
casks: cask/monodraw
casks: cask/notion
casks: cask/notunes
casks: cask/peakhour
casks: cask/slack
casks: cask/spotify
casks: cask/vlc

cask/alfred: alfred/alfred-type-clipboard-workflow
cask/alfred: alfred/alfred-ykman-oath
cask/alfred: alfred/gopass-alfred
cask/alfred: alfred/gpg-start-alfred

net: pacman/bind         # dig
net: brew/dog pacman/dog # dig rust replacement
net: pacman/inetutils    # telnet, ftp
net: brew/iperf pacman/iperf
net: pacman/iproute2  # ip
net: pacman/iptraf-ng # network interface monitoring
net: brew/ldns        # drill - sig with dnssec
net: brew/mosh pacman/mosh
net: brew/mtr         # traceroute and ping
net: pacman/net-tools # ifconfig
net: brew/nmap
net: brew/rsync
net: brew/socat
net: brew/sslscan # scan all cipher suites for https
net: pacman/tcpdump
net: brew/tcptraceroute yay/tcptraceroute
net: brew/telnet
net: brew/termshark yay/termshark
net: brew/testssl # similar to ssltest in terminal
net: pacman/traceroute
net: cask/wireshark pacman/wireshark-cli
net: brew/wrk yay/wrk # http benchmarks - load testing

dev: brew/browser # pipe html to browser
dev: brew/cloc    # stats for code
dev: brew/ctop yay/ctop-bin
dev: cask/dash
dev: brew/direnv yay/direnv
dev: brew/distribution # histograms
dev: pacman/dive       # inspect docker layers
dev: cask/docker
dev: pacman/docker-compose
dev: brew/docker-machine pacman/docker-machine
dev: cask/docker pacman/docker pacman/docker-buildx
dev: volta/doctoc
dev: brew/entr                # watch files and execute - similar to fswatch
dev: brew/fswatch yay/fswatch # watch files and execute
dev: brew/gcc
dev: brew/gettext                    # i18n - internatiolization
dev: brew/git-delta pacman/git-delta # git diff syntax highlighting
dev: brew/git-lfs
dev: uv/git-of-theseus
dev: brew/git-quick-stats yay/git-quick-stats
dev: pacman/gvim # installs GTK/X support for clipboard forwarding
dev: brew/lazydocker yay/lazydocker-bin
dev: brew/lazygit pacman/lazygit
dev: brew/libyaml
dev: pacman/man-pages
dev: cask/neovide
dev: cask/pop # screen sharing conference
dev: cask/postman
dev: uv/pre-commit
dev: yay/regclient-regctl
dev: brew/tmux pacman/tmux
dev: brew/tmux-xpanes yay/tmux-xpanes
dev: brew/universal-ctags pacman/ctags # generates tags from codebase
dev: yay/vale-bin                      # prose linter/spell checker
dev: brew/watchman                     # lib for watching files

devcloud: yay/argo-bin
devcloud: pacman/argocd
devcloud: yay/aws-cli-v2-bin # TODO switch to directly downloading zip
# devcloud: uv/aws-mfa
# devcloud: yay/aws-session-manager-plugin
# devcloud: uv/certbot
# devcloud: yay/chart-testing
devcloud: pacman/eksctl
devcloud: yay/helm
devcloud: pacman/istio
devcloud: pacman/k9s
# devcloud: yay/knative-client-bin
devcloud: yay/krew-bin
devcloud: yay/kubectl
devcloud: yay/kubeswitch-bin
devcloud: pacman/stern # k8s multi-pod logging
# devcloud: brew/tfenv yay/tfenv  # change terraform version

devpy: uv/basedpyright
devpy: uv/check-manifest
devpy: uv/johnnydep # show dep tree
devpy: uv/poetry
devpy: uv/ptpython
devpy: uv/ruff
devpy: uv/twine
devpy: brew/uv pacman/uv

devnode: volta/eslint
devnode: volta/eslint_d
devnode: volta/@fsouza/prettierd
devnode: volta/graphql-language-service-cli
devnode: volta/prettier
devnode: volta/@prisma/language-server
devnode: volta/typescript
devnode: volta/typescript-language-server
devnode: volta/yarn
devnode: volta/yarn-why

devc: brew/llvm # clangd for c language server in coc-vim

devsh: volta/bash-language-server
devsh: uv/shellcheck-py
devsh: brew/shfmt pacman/shfmt

devtf: yay/terraform-ls-bin

devlua: brew/lua-language-server pacman/lua-language-server
devlua: pacman/luarocks
devlua: yay/stylua

devgo: pacman/gopls

devnim: yay/choosenim-bin
devnim: nimble/nimlangserver
devnim: nimble/inim

music: cask/audio-hijack
music: cask/ilok-license-manager
music: cask/loopback
music: cask/soundsource
music: cask/waves-central

brew/browserpass: TAP=amar1729/formulae/
cask/datacolor-spyder-elite: TAP=homebrew/cask-drivers/
brew/dyff: TAP=homeport/tap/

# manually downloading older versions as newer versions changed pandoc AST
# see https://github.com/ickc/pantable
# > Warning: panflute and pantable only support pandoc < 2.10 and is so
# > far incompatible with pandoc 2.10+. This is because there’s a new AST
# > change related to table spans. See https://github.com/jgm/pandoc/issues/1024,
# > https://github.com/sergiocorreia/panflute/issues/142. Until that is resolved,
# > please stick with 2.9.2.1 or below when used together with pantable.

# pandoc: brew/librsvg       # necessary to embed svg images
# pandoc: cask/mactex-no-gui # latex
# pandoc: brew/pandoc
# pandoc: brew/pandoc-citeproc
# pandoc: brew/pandoc-crossref
# pandoc: uv/pandoc-fignos
# pandoc: uv/pandocfilter-sh
# uv/pandoc-fignos: VERSION= < 2.3.1

# $(BREW_PREFIX)/Cellar/pandoc:
# curl -L https://bintray.com/homebrew/bottles/download_file?file_path=pandoc-2.9.2.1.catalina.bottle.tar.gz \
#     | tar -zxv -C /usr/local/Cellar
#
# $(BREW_PREFIX)/Cellar/pandoc-crossref:
# curl -L https://bintray.com/homebrew/bottles/download_file?file_path=pandoc-crossref-0.3.6.4.catalina.bottle.tar.gz \
#     | tar -zxv -C /usr/local/Cellar
#
# $(BREW_PREFIX)/Cellar/pandoc-citeproc:
# curl -L https://bintray.com/homebrew/bottles/download_file?file_path=pandoc-citeproc-0.17.0.1.catalina.bottle.tar.gz \
#     | tar -zxv -C /usr/local/Cellar

# brew/sshuttle  # proxy over ssh
# brew/cipherscan  # scan all cipher suites for https
# brew/dnsperf  # profile dns server
# brew/proxychains-ng  # proxy tcp traffic

# brew/dcraw  # decode raw files
# brew/libmagic
# brew/qrencode  # generate qrcode
# brew/zbar  # reading barcode

# brew/awsprey: TAP=gamechanger/brews/
# brew/brew-gem
# brew/pv  # monitor pipe progress
# brew/rockymadden/rockymadden/slack-cli
# brew/tidy-html5
# brew/um  # personal man pages
# brew/xo/xo/usql  # universal sql client
# brew/xz  # data-compession similar to gzip
# brew/zstd  # data-compression from facebook

# cask/android-platform-tools
# cask/charles # proxy
# cask/chrysalis # keyboardio
# cask/cool-retro-term
# cask/datagrip
# cask/dbeaver-community
# cask/fluor # change fn keys per app
# cask/hazeover # hide all apps
# cask/insomnia # rest apis
# cask/keybase
# cask/moom
# cask/netspot # wifi design
# cask/obs # stream generation
# cask/obs-virtualcam # use stream as webcam input
# cask/openaudible
# cask/openvpn-connect
# cask/serial # serial port connectivity
# cask/signal-beta
# cask/textual # irc
# cask/ukelele # keyboard layout
# cask/vagrant
# cask/virtualbox
# cask/visual-studio-code
# cask/wifi-explorer
# cask/vimr
# casks: cask/cleanmymac
# casks: cask/datacolor-spyder-elite # no longer available as cask

# devnim: yay/choosenim-bin
# devnim: nimble/choosenim
