add_newline = true
command_timeout = 100

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"
vicmd_symbol = "[V](bold green)"

[line_break]
disabled = false

[kubernetes]
disabled = false
detect_files = ["Chart.yaml"]
detect_folders = ["charts", "k8s"]
[kubernetes.context_aliases]
'arn:aws:eks:[\w\d\-]+:[\d]+:cluster/(?P<var_cluster>[\w\d\-_]+)' = 'eks/$var_cluster'
